theme: jekyll-theme-cayman
title: Philippa Grace McCabe
description: Machine Learning Research Group - PhD Researcher at Liverpool John Moores University - Funded by OActive

navbar-links:
  About Me: "aboutme"
  Stuff:
    - Research output: ""
    - Teaching stuff: "http://www.markdowntutorial.com/"
